-- USERS
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(255)                        NOT NULL,
  email VARCHAR(512)                       NOT NULL,
  created_at TIMESTAMP WITHOUT TIME ZONE   NOT NULL DEFAULT NOW(),
  CONSTRAINT pk_users PRIMARY KEY (id),
  CONSTRAINT uq_users_email UNIQUE (email)
);

CREATE INDEX IF NOT EXISTS idx_users_email ON users (email);

-- ITEMS
CREATE TABLE IF NOT EXISTS items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(255)                        NOT NULL,
  description TEXT                         NOT NULL,
  is_available BOOLEAN                     NOT NULL DEFAULT TRUE,
  owner_id BIGINT                          NOT NULL,
  request_id BIGINT                        NULL,
  created_at TIMESTAMP WITHOUT TIME ZONE   NOT NULL DEFAULT NOW(),
  CONSTRAINT pk_items PRIMARY KEY (id),
  CONSTRAINT fk_items_owner
    FOREIGN KEY (owner_id) REFERENCES users (id)
    ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_items_owner      ON items (owner_id);
CREATE INDEX IF NOT EXISTS idx_items_available  ON items (is_available);

-- BOOKINGS
CREATE TABLE IF NOT EXISTS bookings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  start_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  end_date   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  booker_id  BIGINT NOT NULL,
  item_id    BIGINT NOT NULL,
  status     VARCHAR(16) NOT NULL,

  CONSTRAINT fk_bookings_booker
    FOREIGN KEY (booker_id) REFERENCES users (id)
    ON UPDATE CASCADE ON DELETE RESTRICT,

  CONSTRAINT fk_bookings_item
    FOREIGN KEY (item_id) REFERENCES items (id)
    ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_bookings_booker ON bookings (booker_id, start_date DESC);
CREATE INDEX IF NOT EXISTS idx_bookings_item   ON bookings (item_id,   start_date DESC);
CREATE INDEX IF NOT EXISTS idx_bookings_status ON bookings (status);

-- COMMENTS
CREATE TABLE IF NOT EXISTS comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  text TEXT NOT NULL,
  item_id BIGINT NOT NULL,
  author_id BIGINT NOT NULL,
  created TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_comments_item
      FOREIGN KEY (item_id) REFERENCES items(id)
      ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT fk_comments_author
      FOREIGN KEY (author_id) REFERENCES users(id)
      ON UPDATE CASCADE ON DELETE RESTRICT
);